In [2]:
import pandas as pd
#import numpy as np

In [3]:
nse=pd.read_csv('./data/NSE.csv')

In [4]:
nse.head()

         Date      Price       Open       High        Low     Vol. Change %
0  22/12/2023  74,023.27  74,288.88  74,430.47  73,993.49  423.20M   -0.36%
1  21/12/2023  74,289.02  73,397.71  74,292.76  73,397.71  760.93M    1.21%
2  20/12/2023  73,397.71  72,470.10  73,399.61  72,470.10  552.22M    1.28%
3  19/12/2023  72,470.10  72,404.91  72,489.21  72,320.32  411.06M    0.09%
4  18/12/2023  72,404.91  72,389.23  72,413.13  72,276.75  324.15M    0.02%

In [5]:
nse.describe()

              Date      Price       Open       High        Low   Vol. Change %
count         2948       2948       2948       2948       2948   1651     2948
unique        2948       2939       2938       2932       2938   1614      501
top     22/12/2023  29,964.79  20,658.28  37,259.65  37,278.34  1.17B    0.02%
freq             1          2          3          4          3      3       35

In [6]:
print(nse.shape)

(2948, 7)

In [7]:
print(nse.dtypes)

Date        object
Price       object
Open        object
High        object
Low         object
Vol.        object
Change %    object
dtype: object

In [8]:
print(nse.isnull().sum())

Date           0
Price          0
Open           0
High           0
Low            0
Vol.        1297
Change %       0
dtype: int64

# What is the date range — oldest to newest?

In [9]:
nse['Date'] = pd.to_datetime(nse['Date'])
print(nse['Date'].min())
print(nse['Date'].max())

2012-01-30 00:00:00
2023-12-22 00:00:00

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11948\3919074063.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  nse['Date'] = pd.to_datetime(nse['Date'])

# How many records are we dealing with?

In [10]:
nse.size

20636

# What columns do we have?

In [11]:
nse.columns

Index(['Date', 'Price', 'Open', 'High', 'Low', 'Vol.', 'Change %'], dtype='object')

# Where is the data dirty or missing?

In [12]:
nse.isnull().sum()

Date           0
Price          0
Open           0
High           0
Low            0
Vol.        1297
Change %       0
dtype: int64

# Which company has the highest average closing price?

In [13]:
nse['Price'] = nse['Price'].str.replace(',', '').astype(float)

In [14]:
nse

           Date     Price       Open       High        Low     Vol. Change %
0    2023-12-22  74023.27  74,288.88  74,430.47  73,993.49  423.20M   -0.36%
1    2023-12-21  74289.02  73,397.71  74,292.76  73,397.71  760.93M    1.21%
2    2023-12-20  73397.71  72,470.10  73,399.61  72,470.10  552.22M    1.28%
3    2023-12-19  72470.10  72,404.91  72,489.21  72,320.32  411.06M    0.09%
4    2023-12-18  72404.91  72,389.23  72,413.13  72,276.75  324.15M    0.02%
...         ...       ...        ...        ...        ...      ...      ...
2943 2012-02-03  20877.64  20,822.00  20,863.93  20,786.35      NaN    0.27%
2944 2012-02-02  20822.00  20,872.94  20,900.58  20,785.40      NaN    0.15%
2945 2012-02-01  20790.88  20,875.34  20,941.03  20,790.88      NaN   -0.41%
2946 2012-01-31  20875.83  20,818.56  21,009.92  20,789.48      NaN    0.70%
2947 2012-01-30  20731.72  20,939.10  20,950.02  20,731.72      NaN   -0.77%

[2948 rows x 7 columns]

In [15]:

nse['Date'] = pd.to_datetime(nse['Date'])
nse['Year'] = nse['Date'].dt.year
print(nse.groupby('Year')['Price'].mean())

Year
2012    23434.316245
2013    35826.621538
2014    39258.733750
2015    30819.451984
2016    26549.630972
2017    31775.304656
2018    37407.520726
2019    28859.278704
2020    27114.844217
2021    40035.034758
2022    48549.354758
2023    60980.900329
Name: Price, dtype: float64

# How many trading days are in this dataset?

In [16]:
len(nse['Date'])

2948

# What is the date range — oldest to newest?

In [17]:
print(nse['Date'].min())
print(nse['Date'].max())

2012-01-30 00:00:00
2023-12-22 00:00:00

In [18]:
print(f"from {nse['Date'].min()} to  {nse['Date'].max()}")

from 2012-01-30 00:00:00 to  2023-12-22 00:00:00

# Are there any missing values?

In [19]:
nse.isna().sum()

Date           0
Price          0
Open           0
High           0
Low            0
Vol.        1297
Change %       0
Year           0
dtype: int64

In [20]:
print(nse.dtypes)

Date        datetime64[ns]
Price              float64
Open                object
High                object
Low                 object
Vol.                object
Change %            object
Year                 int32
dtype: object

# What was the highest price the NSE ever reached?

In [21]:
nse['Price'].max()

np.float64(74289.02)

# What was the lowest price ever?

In [22]:
nse['Price'].min()

np.float64(20123.51)

# What is the average daily price overall?

In [23]:
print(nse['Price'].mean())

35927.630332428766

# Which date had the highest trading volume?

In [24]:
nse['Vol.'] = nse['Vol.'].str.replace('M', '').str.strip()

In [25]:
print(nse['Vol.'].unique())

['423.20' '760.93' '552.22' ... '262.61' '230.13' '466.94']

In [26]:
nse['Vol.'] = pd.to_numeric(nse['Vol.'], errors='coerce')

In [27]:
nse.groupby('Vol.')['Date'].max()

Vol.
51.88    2022-09-21
59.50    2017-09-05
62.09    2017-01-04
67.37    2022-09-19
70.94    2016-10-21
            ...
942.72   2017-11-27
944.86   2018-01-26
960.68   2018-01-17
973.58   2023-03-30
998.08   2023-06-30
Name: Date, Length: 1579, dtype: datetime64[ns]

In [28]:
print(nse.loc[nse['Vol.'] == nse['Vol.'].max(), 'Date'])

123   2023-06-30
Name: Date, dtype: datetime64[ns]

# What was the best single day — highest positive change?

In [29]:
nse

,Date,Price,Open,High,Low,Vol.,Change %,Year
0,2023-12-22,74023.27,"74,288.88","74,430.47","73,993.49",423.20,-0.36%,2023
1,2023-12-21,74289.02,"73,397.71","74,292.76","73,397.71",760.93,1.21%,2023
2,2023-12-20,73397.71,"72,470.10","73,399.61","72,470.10",552.22,1.28%,2023
3,2023-12-19,72470.10,"72,404.91","72,489.21","72,320.32",411.06,0.09%,2023
4,2023-12-18,72404.91,"72,389.23","72,413.13","72,276.75",324.15,0.02%,2023
...,...,...,...,...,...,...,...,...
2943,2012-02-03,20877.64,"20,822.00","20,863.93","20,786.35",NaN,0.27%,2012
2944,2012-02-02,20822.00,"20,872.94","20,900.58","20,785.40",NaN,0.15%,2012
2945,2012-02-01,20790.88,"20,875.34","20,941.03","20,790.88",NaN,-0.41%,2012
2946,2012-01-31,20875.83,"20,818.56","21,009.92","20,789.48",NaN,0.70%,2012
2947,2012-01-30,20731.72,"20,939.10","20,950.02","20,731.72",NaN,-0.77%,2012

In [30]:
nse['Change %'] = nse['Change %'].str.replace('%', '').str.strip().astype(float)

In [31]:
print(nse[['Date', 'Change %']].loc[nse['Change %'].idxmax()])

Date        2015-04-01 00:00:00
Change %                   8.31
Name: 2161, dtype: object

# What was the worst single day  biggest crash?

In [32]:
print(nse[['Date', 'Change %']].loc[nse['Change %'].idxmin()])

Date        2020-03-10 00:00:00
Change %                  -4.91
Name: 939, dtype: object

# How many days had a negative change?

In [33]:
print((nse['Change %'] < 0).sum())

1435

 # How many days had a positive change?

In [34]:
print((nse['Change %'] > 0).sum())

1485

# What was the average price per year?

In [40]:
print(nse.groupby('Year')['Change %'].mean())

Year
2012    0.131441
2013    0.160526
2014   -0.065161
2015   -0.069393
2016   -0.019231
2017    0.147814
2018   -0.074274
2019   -0.060810
2020    0.170040
2021    0.025847
2022    0.076573
2023    0.154815
Name: Change %, dtype: float64

# Which year was the best for the market?

In [ ]:
print(nse.groupby('Year')['Change %'].mean().idxmax())

2020

# Which year was the worst?

In [42]:
print(nse.groupby('Year')['Change %'].mean().idxmin())

2018

# Is the Nigerian stock market growing or dying

In [43]:
print(nse.groupby('Year')['Price'].mean().sort_index())

Year
2012    23434.316245
2013    35826.621538
2014    39258.733750
2015    30819.451984
2016    26549.630972
2017    31775.304656
2018    37407.520726
2019    28859.278704
2020    27114.844217
2021    40035.034758
2022    48549.354758
2023    60980.900329
Name: Price, dtype: float64

it's going up properly